/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example

fun main() {
    val lit1 = Initial.Literal(Initial.StrLit("A"))
    val expr1 = Initial.Binary(
        Initial.Paren(lit1),
        "+",
        Initial.Paren(Initial.Paren(lit1))
    )

    println(Initial.flatten(expr1))

    val lit2 = GenericTraversals.Literal<Nothing>(GenericTraversals.StrLit("A"))
    val expr2 = GenericTraversals.Binary(
        GenericTraversals.Paren(lit2),
        "+",
        GenericTraversals.Paren(GenericTraversals.Paren(lit2))
    )

    println(GenericTraversals.flatten(expr2))
    println(GenericTraversals.count(expr2))
}
