/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test fun initial() {
        val lit = Initial.Literal(Initial.StrLit("A"))
        val expr = Initial.Binary(
            Initial.Paren(lit),
            "+",
            Initial.Paren(Initial.Paren(lit))
        )

        val expected = Initial.Binary(
            lit,
            "+",
            lit
        )

        assertEquals(expected, Initial.flatten(expr))
    }

    @Test fun genericTraversals() {
        val lit = GenericTraversals.Literal<Nothing>(GenericTraversals.StrLit("A"))
        val expr = GenericTraversals.Binary(
            GenericTraversals.Paren(lit),
            "+",
            GenericTraversals.Paren(GenericTraversals.Paren(lit))
        )

        val expected = GenericTraversals.Binary(
            lit,
            "+",
            lit
        )

        assertEquals(expected, GenericTraversals.flatten(expr))
        assertEquals(expected, GenericTraversals.flattenViaCata(expr))
        assertEquals(expected, GenericTraversals.flattenViaCata2(expr))
        assertEquals(6, GenericTraversals.count(expr))
    }
}
